colours-production:
  configFile: ~/.ssh/config
  stage: production
  branch: master
  deploy_path: ~/{{application}}

local:
  local: true
  stage: local
  branch: master
  deploy_path: ~/localdeploys/{{application}}
