production:
  configFile: ~/.ssh/config
  stage: production
  branch: master
  http_user:
  deploy_path:
  slack_webhook:

local:
  local: true
  stage: local
  branch: master
  deploy_path: ~/localdeploys/{{application}}
